Мещанов Task6
HugoLoud/spbu-python-course pull request #7
Opened 2024-11-10 20:56 UTC by HugoLoud

# Задача 6. Декартово дерево

* **Дедлайн**: 10.11.2024, 23:59
* Полный балл: 13

## Задача

- [x] Реализовать **декартово дерево**
  - [Здесь можно почитать про структуру](https://neerc.ifmo.ru/wiki/index.php?title=Декартово_дерево)
  - [x] Структура должна реализовывать MutableMapping
  - [x] Реализуйте прямой и обратный итераторы (обходы)
    - `__iter__` должен возвращать прямой
  - [x] Взаимодействие с элементами через []
  - [x] Проверку ключа через оператор `in`

2024-11-15 09:04 UTC, Krekep requested changes
Необходимы исправления

2024-11-15 09:04 UTC, Krekep commented on project/treap.py
> +    """
Документация должна быть на английском

2024-11-15 09:04 UTC, Krekep commented on project/treap.py
> +    def __getitem__(self, key):
Не хватает аннотации типов

2024-11-15 09:04 UTC, Krekep commented on project/treap.py
> +        """
Не полная документация

2024-12-18 00:06 UTC, HugoLoud commented on project/treap.py
> +    """
Понял, все перевел

2024-12-18 00:06 UTC, HugoLoud commented on project/treap.py
> +        """
Расширил документацию

2024-12-18 00:06 UTC, HugoLoud commented on project/treap.py
> +    def __getitem__(self, key):
Исправил

2024-12-18 09:15 UTC, Krekep approved these changes
Зачтено

2026-04-04 10:19 UTC, merged